// Copyright 2026 privaelo
//
// Loads the static occupancy grid generated by scripts/gen_world.py
// (config/cluttered.map.yaml + matching .pgm) and latches it on `map` for
// global_planner. Reads only the fixed 7-key flat format gen_world.py emits,
// not general YAML/nav2 map_server format — no yaml-cpp dependency needed
// for a format this repo fully controls the shape of.

#include <cstdint>
#include <fstream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <nav_msgs/msg/occupancy_grid.hpp>
#include <rclcpp/rclcpp.hpp>

namespace
{

struct MapMeta
{
  std::string image;
  double resolution{};
  double origin_x{}, origin_y{};
  int negate{};
  double occupied_thresh{}, free_thresh{};
};

std::string trim(const std::string & s)
{
  const auto begin = s.find_first_not_of(" \t\r\n");
  if (begin == std::string::npos) {
    return "";
  }
  const auto end = s.find_last_not_of(" \t\r\n");
  return s.substr(begin, end - begin + 1);
}

MapMeta read_map_yaml(const std::string & path)
{
  std::ifstream f(path);
  if (!f) {
    throw std::runtime_error("cannot open map_yaml: " + path);
  }

  MapMeta meta;
  std::string line;
  while (std::getline(f, line)) {
    const auto colon = line.find(':');
    if (colon == std::string::npos) {
      continue;
    }
    const std::string key = trim(line.substr(0, colon));
    const std::string value = trim(line.substr(colon + 1));
    if (key == "image") {
      meta.image = value;
    } else if (key == "resolution") {
      meta.resolution = std::stod(value);
    } else if (key == "origin") {
      // "[x, y, z]"
      const auto lb = value.find('[');
      const auto rb = value.find(']');
      std::istringstream iss(value.substr(lb + 1, rb - lb - 1));
      std::string tok;
      std::getline(iss, tok, ',');
      meta.origin_x = std::stod(tok);
      std::getline(iss, tok, ',');
      meta.origin_y = std::stod(tok);
    } else if (key == "negate") {
      meta.negate = std::stoi(value);
    } else if (key == "occupied_thresh") {
      meta.occupied_thresh = std::stod(value);
    } else if (key == "free_thresh") {
      meta.free_thresh = std::stod(value);
    }
  }
  if (meta.image.empty() || meta.resolution <= 0.0) {
    throw std::runtime_error("map_yaml missing required fields: " + path);
  }
  return meta;
}

// Binary P5 PGM, fixed header shape written by gen_world.py: "P5\n{w} {h}\n255\n".
struct Pgm
{
  int width{}, height{};
  std::vector<uint8_t> pixels;
};

Pgm read_pgm(const std::string & path)
{
  std::ifstream f(path, std::ios::binary);
  if (!f) {
    throw std::runtime_error("cannot open pgm: " + path);
  }
  std::string magic;
  int maxval{};
  Pgm pgm;
  f >> magic >> pgm.width >> pgm.height >> maxval;
  if (magic != "P5" || pgm.width <= 0 || pgm.height <= 0) {
    throw std::runtime_error("unsupported pgm header: " + path);
  }
  f.get();  // single whitespace byte separating header from binary data
  pgm.pixels.resize(static_cast<size_t>(pgm.width) * pgm.height);
  f.read(reinterpret_cast<char *>(pgm.pixels.data()), pgm.pixels.size());
  if (!f) {
    throw std::runtime_error("pgm shorter than width*height: " + path);
  }
  return pgm;
}

std::string dirname(const std::string & path)
{
  const auto slash = path.find_last_of('/');
  return slash == std::string::npos ? "." : path.substr(0, slash);
}

}  // namespace

class MapLoader : public rclcpp::Node
{
public:
  MapLoader()
  : Node("map_loader")
  {
    const std::string map_yaml = declare_parameter("map_yaml", std::string());
    const std::string frame_id = declare_parameter("frame_id", std::string("map"));
    if (map_yaml.empty()) {
      throw std::invalid_argument("map_yaml parameter is required");
    }

    const MapMeta meta = read_map_yaml(map_yaml);
    const Pgm pgm = read_pgm(dirname(map_yaml) + "/" + meta.image);

    RCLCPP_INFO(
      get_logger(),
      "loaded %s: %dx%d cells, resolution %.3f m, origin (%.2f, %.2f), frame '%s'",
      map_yaml.c_str(), pgm.width, pgm.height, meta.resolution, meta.origin_x, meta.origin_y,
      frame_id.c_str());

    nav_msgs::msg::OccupancyGrid grid;
    grid.header.frame_id = frame_id;
    grid.header.stamp = now();
    grid.info.resolution = static_cast<float>(meta.resolution);
    grid.info.width = static_cast<uint32_t>(pgm.width);
    grid.info.height = static_cast<uint32_t>(pgm.height);
    grid.info.origin.position.x = meta.origin_x;
    grid.info.origin.position.y = meta.origin_y;
    grid.info.origin.orientation.w = 1.0;
    grid.data.resize(static_cast<size_t>(pgm.width) * pgm.height);

    // OccupancyGrid row 0 is the origin (bottom); pgm row 0 is the top of the
    // image, so row order is flipped during conversion.
    for (int row = 0; row < pgm.height; ++row) {
      const int pgm_row = pgm.height - 1 - row;
      for (int col = 0; col < pgm.width; ++col) {
        const uint8_t pixel = pgm.pixels[static_cast<size_t>(pgm_row) * pgm.width + col];
        const double value = meta.negate ?
          pixel / 255.0 :
          (255.0 - pixel) / 255.0;
        int8_t occ = -1;
        if (value > meta.occupied_thresh) {
          occ = 100;
        } else if (value < meta.free_thresh) {
          occ = 0;
        }
        grid.data[static_cast<size_t>(row) * pgm.width + col] = occ;
      }
    }

    const auto qos = rclcpp::QoS(rclcpp::KeepLast(1)).reliable().transient_local();
    map_pub_ = create_publisher<nav_msgs::msg::OccupancyGrid>("map", qos);
    map_pub_->publish(grid);
  }

private:
  rclcpp::Publisher<nav_msgs::msg::OccupancyGrid>::SharedPtr map_pub_;
};

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  auto node = std::make_shared<MapLoader>();
  rclcpp::spin(node);
  rclcpp::shutdown();
  return 0;
}
